# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"
gem 'rubocop', require: false # because it is a standalone tool, use require = false

gem 'rubocop-performance', require: false
